import type {
  Lead,
  LeadSummary,
  OutreachMessage,
  ICPProfile,
  UserSettings,
} from '@/types';

// ── Default new fields (shared across dummy records) ──────────────────────────

const DEFAULT_LEAD_EXTRAS: Pick<
  Lead,
  | 'emailVerificationStatus'
  | 'jobTitleMatchScore' | 'industryMatchScore' | 'companySizeMatchScore'
  | 'painMatchScore' | 'activitySignalsScore'
  | 'qualificationStatus' | 'qualificationNotes'
  | 'icpProfileId' | 'matchedCriteria' | 'mismatchReasons'
  | 'handoffStatus' | 'handoffTarget' | 'handoffNotes' | 'handoffAt'
> = {
  emailVerificationStatus: 'Unknown',
  jobTitleMatchScore: 0,
  industryMatchScore: 0,
  companySizeMatchScore: 0,
  painMatchScore: 0,
  activitySignalsScore: 0,
  qualificationStatus: 'Unknown',
  qualificationNotes: null,
  icpProfileId: null,
  matchedCriteria: null,
  mismatchReasons: null,
  handoffStatus: 'NotReady',
  handoffTarget: null,
  handoffNotes: null,
  handoffAt: null,
};

// ── Leads ─────────────────────────────────────────────────────────────────────

export const DUMMY_LEADS: Lead[] = [
  {
    id: '1',
    firstName: 'Sarah',
    lastName: 'Chen',
    email: 'sarah.chen@techcorp.io',
    phone: '+1 (415) 555-0189',
    whatsapp: null,
    jobTitle: 'VP of Engineering',
    company: 'TechCorp',
    companyWebsite: 'https://techcorp.io',
    industry: 'Software & Technology',
    companySize: '51–200 employees',
    geography: 'San Francisco, CA',
    revenueRange: '$5M–$20M ARR',
    linkedInUrl: 'https://linkedin.com/in/sarah-chen',
    source: 'LinkedIn',
    status: 'Qualified',
    enrichmentStatus: 'Enriched',
    classification: 'Hot',
    notes: 'Met at SaaStr Annual. Strong interest in AI outreach tooling. Follow up after product demo.',
    importedAt: '2025-04-15T10:00:00Z',
    icpScore: 87,
    scoreBreakdown: {
      jobTitleMatch: 28,
      industryMatch: 22,
      companySizeMatch: 13,
      painMatch: 16,
      activitySignals: 8,
      total: 87,
    },
    ...DEFAULT_LEAD_EXTRAS,
    jobTitleMatchScore: 28,
    industryMatchScore: 22,
    companySizeMatchScore: 13,
    painMatchScore: 16,
    activitySignalsScore: 8,
    emailVerificationStatus: 'Verified',
    qualificationStatus: 'QualifiedLead',
  },
  {
    id: '2',
    firstName: 'Marcus',
    lastName: 'Reyes',
    email: 'm.reyes@scalestartup.com',
    phone: '+1 (512) 555-0274',
    whatsapp: '+1 (512) 555-0274',
    jobTitle: 'CTO',
    company: 'ScaleStartup',
    companyWebsite: 'https://scalestartup.com',
    industry: 'SaaS / Cloud',
    companySize: '11–50 employees',
    geography: 'Austin, TX',
    revenueRange: '$1M–$5M ARR',
    linkedInUrl: 'https://linkedin.com/in/marcus-reyes',
    source: 'LinkedIn',
    status: 'Contacted',
    enrichmentStatus: 'Enriched',
    classification: 'Warm',
    notes: null,
    importedAt: '2025-04-14T09:30:00Z',
    icpScore: 74,
    scoreBreakdown: {
      jobTitleMatch: 25,
      industryMatch: 20,
      companySizeMatch: 10,
      painMatch: 14,
      activitySignals: 5,
      total: 74,
    },
    ...DEFAULT_LEAD_EXTRAS,
    jobTitleMatchScore: 25,
    industryMatchScore: 20,
    companySizeMatchScore: 10,
    painMatchScore: 14,
    activitySignalsScore: 5,
    emailVerificationStatus: 'Verified',
  },
  {
    id: '3',
    firstName: 'Priya',
    lastName: 'Sharma',
    email: 'priya@growthco.com',
    phone: null,
    whatsapp: null,
    jobTitle: 'Head of Sales',
    company: 'GrowthCo',
    companyWebsite: 'https://growthco.com',
    industry: 'Sales & Marketing',
    companySize: '51–200 employees',
    geography: 'New York, NY',
    revenueRange: '$5M–$20M ARR',
    linkedInUrl: 'https://linkedin.com/in/priya-sharma',
    source: 'LinkedIn',
    status: 'New',
    enrichmentStatus: 'Unknown',
    classification: null,
    notes: null,
    importedAt: '2025-04-16T14:00:00Z',
    icpScore: null,
    scoreBreakdown: null,
    ...DEFAULT_LEAD_EXTRAS,
  },
  {
    id: '4',
    firstName: 'David',
    lastName: 'Kim',
    email: 'd.kim@cloudbase.io',
    phone: '+1 (206) 555-0143',
    whatsapp: null,
    jobTitle: 'Director of Operations',
    company: 'CloudBase',
    companyWebsite: 'https://cloudbase.io',
    industry: 'Cloud Infrastructure',
    companySize: '201–500 employees',
    geography: 'Seattle, WA',
    revenueRange: '$20M–$50M ARR',
    linkedInUrl: 'https://linkedin.com/in/david-kim',
    source: 'LinkedIn',
    status: 'Qualified',
    enrichmentStatus: 'Enriched',
    classification: 'Hot',
    notes: 'Referred by David Park at Sequoia. High priority — schedule demo this week.',
    importedAt: '2025-04-13T08:00:00Z',
    icpScore: 91,
    scoreBreakdown: {
      jobTitleMatch: 27,
      industryMatch: 24,
      companySizeMatch: 14,
      painMatch: 18,
      activitySignals: 8,
      total: 91,
    },
    ...DEFAULT_LEAD_EXTRAS,
    jobTitleMatchScore: 27,
    industryMatchScore: 24,
    companySizeMatchScore: 14,
    painMatchScore: 18,
    activitySignalsScore: 8,
    emailVerificationStatus: 'Verified',
    qualificationStatus: 'QualifiedLead',
    handoffStatus: 'Ready',
  },
  {
    id: '5',
    firstName: 'Emma',
    lastName: 'Wilson',
    email: 'emma.w@dataflow.co',
    phone: null,
    whatsapp: null,
    jobTitle: 'Marketing Manager',
    company: 'DataFlow Inc',
    companyWebsite: 'https://dataflow.co',
    industry: 'Data & Analytics',
    companySize: '11–50 employees',
    geography: 'Boston, MA',
    revenueRange: '$1M–$5M ARR',
    linkedInUrl: null,
    source: 'Manual',
    status: 'Disqualified',
    enrichmentStatus: 'Partial',
    classification: 'Reject',
    notes: 'Not a decision maker. Company too small and outside target industry.',
    importedAt: '2025-04-12T11:00:00Z',
    icpScore: 31,
    scoreBreakdown: {
      jobTitleMatch: 8,
      industryMatch: 12,
      companySizeMatch: 5,
      painMatch: 4,
      activitySignals: 2,
      total: 31,
    },
    ...DEFAULT_LEAD_EXTRAS,
    jobTitleMatchScore: 8,
    industryMatchScore: 12,
    companySizeMatchScore: 5,
    painMatchScore: 4,
    activitySignalsScore: 2,
    qualificationStatus: 'NotQualified',
    emailVerificationStatus: 'Unverified',
  },
  {
    id: '6',
    firstName: 'James',
    lastName: "O'Brien",
    email: 'james@fintechhub.com',
    phone: '+1 (312) 555-0361',
    whatsapp: '+1 (312) 555-0361',
    jobTitle: 'CFO',
    company: 'FinTechHub',
    companyWebsite: 'https://fintechhub.com',
    industry: 'Financial Technology',
    companySize: '501–1000 employees',
    geography: 'Chicago, IL',
    revenueRange: '$50M+ ARR',
    linkedInUrl: 'https://linkedin.com/in/james-obrien',
    source: 'LinkedIn',
    status: 'New',
    enrichmentStatus: 'Unknown',
    classification: null,
    notes: null,
    importedAt: '2025-04-17T16:45:00Z',
    icpScore: null,
    scoreBreakdown: null,
    ...DEFAULT_LEAD_EXTRAS,
  },
  {
    id: '7',
    firstName: 'Aisha',
    lastName: 'Patel',
    email: 'aisha.patel@saasworks.io',
    phone: '+44 20 7946 0289',
    whatsapp: '+44 20 7946 0289',
    jobTitle: 'Product Manager',
    company: 'SaasWorks',
    companyWebsite: 'https://saasworks.io',
    industry: 'SaaS / Cloud',
    companySize: '51–200 employees',
    geography: 'London, UK',
    revenueRange: '$5M–$20M ARR',
    linkedInUrl: 'https://linkedin.com/in/aisha-patel',
    source: 'LinkedIn',
    status: 'Contacted',
    enrichmentStatus: 'Enriched',
    classification: 'Warm',
    notes: null,
    importedAt: '2025-04-11T13:20:00Z',
    icpScore: 61,
    scoreBreakdown: {
      jobTitleMatch: 20,
      industryMatch: 16,
      companySizeMatch: 12,
      painMatch: 10,
      activitySignals: 3,
      total: 61,
    },
    ...DEFAULT_LEAD_EXTRAS,
    jobTitleMatchScore: 20,
    industryMatchScore: 16,
    companySizeMatchScore: 12,
    painMatchScore: 10,
    activitySignalsScore: 3,
    qualificationStatus: 'Nurturing',
  },
  {
    id: '8',
    firstName: 'Ryan',
    lastName: 'Torres',
    email: 'ryan@elevateagency.co',
    phone: '+1 (310) 555-0178',
    whatsapp: null,
    jobTitle: 'CEO',
    company: 'Elevate Agency',
    companyWebsite: 'https://elevateagency.co',
    industry: 'Advertising & Media',
    companySize: '1–10 employees',
    geography: 'Los Angeles, CA',
    revenueRange: null,
    linkedInUrl: 'https://linkedin.com/in/ryan-torres',
    source: 'Manual',
    status: 'New',
    enrichmentStatus: 'Partial',
    classification: 'Cold',
    notes: null,
    importedAt: '2025-04-18T09:10:00Z',
    icpScore: 55,
    scoreBreakdown: {
      jobTitleMatch: 22,
      industryMatch: 14,
      companySizeMatch: 5,
      painMatch: 10,
      activitySignals: 4,
      total: 55,
    },
    ...DEFAULT_LEAD_EXTRAS,
    jobTitleMatchScore: 22,
    industryMatchScore: 14,
    companySizeMatchScore: 5,
    painMatchScore: 10,
    activitySignalsScore: 4,
  },
];

export const DUMMY_LEAD_SUMMARIES: LeadSummary[] = DUMMY_LEADS.map((l) => ({
  id: l.id,
  firstName: l.firstName,
  lastName: l.lastName,
  email: l.email,
  company: l.company,
  jobTitle: l.jobTitle,
  status: l.status,
  source: l.source,
  importedAt: l.importedAt,
  icpScore: l.icpScore,
  classification: l.classification,
  enrichmentStatus: l.enrichmentStatus,
  emailVerificationStatus: l.emailVerificationStatus,
}));

// ── Outreach ──────────────────────────────────────────────────────────────────

export const DUMMY_OUTREACH: OutreachMessage[] = [
  {
    id: 'o1',
    leadId: '1',
    subject: 'Quick intro — TechCorp × Hook Leads',
    body: `Hi Sarah,\n\nI came across your profile and was really impressed by what you and the team at TechCorp are building. Given your background in engineering leadership, I thought Hook Leads might be a great fit for how you approach pipeline.\n\nWe help teams score and prioritize inbound leads using AI, then generate personalised outreach in seconds. I'd love to show you how it works.\n\nWould you be open to a quick 20-minute call this week?\n\nBest,\nYazan`,
    status: 'Sent',
    createdAt: '2025-04-16T11:00:00Z',
    sentAt: '2025-04-16T11:30:00Z',
  },
  {
    id: 'o2',
    leadId: '1',
    subject: 'Following up — Hook Leads',
    body: `Hi Sarah,\n\nJust following up on my message from last week. I know you're busy, so I'll keep this brief.\n\nWe recently helped a team similar to TechCorp reduce their lead qualification time by 60%. Happy to share specifics if that's relevant to where you're focused right now.\n\nLet me know if a quick call makes sense.\n\nBest,\nYazan`,
    status: 'Draft',
    createdAt: '2025-04-22T09:00:00Z',
    sentAt: null,
  },
  {
    id: 'o3',
    leadId: '2',
    subject: 'AI-assisted lead scoring for ScaleStartup',
    body: `Hi Marcus,\n\nI noticed ScaleStartup's recent growth and wanted to reach out. As CTO, you're likely thinking a lot about tooling efficiency right now.\n\nHook Leads uses AI to score and prioritise your leads, then writes personalised outreach messages automatically. It's built for fast-moving teams.\n\nWorth a 15-minute chat?\n\nBest,\nYazan`,
    status: 'Sent',
    createdAt: '2025-04-15T14:00:00Z',
    sentAt: '2025-04-15T14:20:00Z',
  },
  {
    id: 'o4',
    leadId: '2',
    subject: 'Pilot access — 30 days free',
    body: `Hi Marcus,\n\nWanted to circle back one more time. We're running a limited pilot with 5 companies this quarter and I think ScaleStartup could be a strong fit.\n\nThe pilot gives you full access to the platform for 30 days at no cost. Let me know if you'd like to learn more.\n\nBest,\nYazan`,
    status: 'Draft',
    createdAt: '2025-04-21T10:00:00Z',
    sentAt: null,
  },
  {
    id: 'o5',
    leadId: '4',
    subject: 'Intro via David Park — Hook Leads',
    body: `Hi David,\n\nDavid Park suggested I reach out. He thought Hook Leads could be a great fit for CloudBase given your growth trajectory.\n\nIn short: we help ops and sales teams qualify inbound leads 10x faster using AI scoring, and auto-generate personalised outreach messages.\n\nWould love to get 20 minutes on the calendar. Happy to work around your schedule.\n\nBest,\nYazan`,
    status: 'Sent',
    createdAt: '2025-04-14T09:00:00Z',
    sentAt: '2025-04-14T09:30:00Z',
  },
  {
    id: 'o6',
    leadId: '7',
    subject: 'Product teams + AI outreach — a fit?',
    body: `Hi Aisha,\n\nI came across SaasWorks and was impressed by your product roadmap focus. I'm reaching out because we've been working with several product-led growth teams to streamline their outbound motion.\n\nHook Leads scores your leads by ICP fit and drafts personalised messages in seconds. Could save your team meaningful time each week.\n\nOpen to a quick intro call?\n\nBest,\nYazan`,
    status: 'Sent',
    createdAt: '2025-04-12T15:00:00Z',
    sentAt: '2025-04-12T16:00:00Z',
  },
];

// ── ICP Profile ───────────────────────────────────────────────────────────────

export const DUMMY_ICP_PROFILE: ICPProfile = {
  id: 'icp-1',
  name: 'Primary ICP',
  industries: ['SaaS / Cloud', 'Software & Technology', 'Cloud Infrastructure', 'FinTech'],
  jobTitles: ['CTO', 'VP of Engineering', 'Director of Operations', 'CEO', 'VP of Product'],
  companySizeMin: 11,
  companySizeMax: 500,
  locations: ['North America', 'Europe', 'United Kingdom'],
  decisionMaker: true,
  painPoints: [
    'manual lead qualification',
    'slow outreach response times',
    'poor lead scoring accuracy',
    'disconnected CRM tools',
    'sales pipeline visibility',
  ],
  budgetMin: 500,
  budgetMax: 5000,
  buyingTriggers: [
    'recent funding round',
    'team expansion',
    'new GTM hire',
    'switching CRM',
    'missed sales targets',
  ],
  updatedAt: '2025-04-10T09:00:00Z',
};

// ── ICP Profiles (multi-profile list) ─────────────────────────────────────────

export const DUMMY_ICP_PROFILES: ICPProfile[] = [
  {
    id: 'icp-1',
    name: 'Primary ICP',
    industries: ['SaaS / Cloud', 'Software & Technology', 'Cloud Infrastructure', 'FinTech'],
    jobTitles: ['CTO', 'VP of Engineering', 'Director of Operations', 'CEO', 'VP of Product'],
    companySizeMin: 11,
    companySizeMax: 500,
    locations: ['North America', 'Europe', 'United Kingdom'],
    decisionMaker: true,
    painPoints: [
      'manual lead qualification',
      'slow outreach response times',
      'poor lead scoring accuracy',
      'disconnected CRM tools',
      'sales pipeline visibility',
    ],
    budgetMin: 500,
    budgetMax: 5000,
    buyingTriggers: [
      'recent funding round',
      'team expansion',
      'new GTM hire',
      'switching CRM',
      'missed sales targets',
    ],
    updatedAt: '2025-04-10T09:00:00Z',
  },
  {
    id: 'icp-2',
    name: 'Enterprise ICP',
    industries: ['Enterprise Software', 'Financial Services', 'Healthcare IT', 'Manufacturing'],
    jobTitles: ['CIO', 'VP of IT', 'Director of Technology', 'Chief Digital Officer', 'IT Manager'],
    companySizeMin: 500,
    companySizeMax: 10000,
    locations: ['United States', 'Western Europe', 'Australia', 'Canada'],
    decisionMaker: true,
    painPoints: [
      'legacy system modernization',
      'data security compliance',
      'IT budget optimization',
      'integration complexity',
      'slow procurement cycles',
    ],
    budgetMin: 5000,
    budgetMax: 50000,
    buyingTriggers: [
      'digital transformation initiative',
      'compliance requirement',
      'security audit failure',
      'budget approval cycle',
      'vendor contract expiry',
    ],
    updatedAt: '2025-03-22T14:00:00Z',
  },
  {
    id: 'icp-3',
    name: 'SMB Growth ICP',
    industries: ['E-commerce', 'Retail', 'Professional Services', 'Consulting'],
    jobTitles: ['CEO', 'Founder', 'Owner', 'Head of Marketing', 'Growth Manager'],
    companySizeMin: 1,
    companySizeMax: 50,
    locations: ['United States', 'Canada'],
    decisionMaker: true,
    painPoints: [
      'high customer acquisition cost',
      'manual outreach processes',
      'limited sales team bandwidth',
      'no lead scoring system',
      'low email response rates',
    ],
    budgetMin: 100,
    budgetMax: 1000,
    buyingTriggers: [
      'growth plateau',
      'new product launch',
      'competitor pressure',
      'first sales hire',
      'missing revenue targets',
    ],
    updatedAt: '2025-04-02T10:30:00Z',
  },
];

// ── User Settings ─────────────────────────────────────────────────────────────

export const DUMMY_USER_SETTINGS: UserSettings = {
  firstName: 'Yazan',
  lastName: 'Naim',
  email: 'yazan@hookleads.io',
  role: 'Admin',
  timezone: 'America/New_York',
  language: 'en',
  notifications: {
    newLeads: true,
    outreachDrafts: true,
    weeklyDigest: false,
    emailAlerts: true,
  },
};

// ── Aggregates ────────────────────────────────────────────────────────────────

const scoredLeads = DUMMY_LEADS.filter((l) => l.icpScore !== null);

export const SCORE_DISTRIBUTION = {
  high:     scoredLeads.filter((l) => (l.icpScore ?? 0) >= 70).length,
  medium:   scoredLeads.filter((l) => (l.icpScore ?? 0) >= 45 && (l.icpScore ?? 0) < 70).length,
  low:      scoredLeads.filter((l) => (l.icpScore ?? 0) < 45).length,
  unscored: DUMMY_LEADS.filter((l) => l.icpScore === null).length,
};

export const DASHBOARD_STATS = {
  totalLeads:     DUMMY_LEADS.length,
  hotLeads:       DUMMY_LEADS.filter((l) => l.classification === 'Hot').length,
  qualifiedLeads: DUMMY_LEADS.filter((l) => l.status === 'Qualified').length,
  outreachSent:   DUMMY_OUTREACH.filter((o) => o.status === 'Sent').length,
  outreachDrafts: DUMMY_OUTREACH.filter((o) => o.status === 'Draft').length,
  replyRate:      34,
  avgIcpScore:    Math.round(
    scoredLeads.reduce((sum, l) => sum + (l.icpScore ?? 0), 0) / scoredLeads.length,
  ),
  conversionRate: Math.round(
    (DUMMY_LEADS.filter((l) => l.status === 'Qualified').length / DUMMY_LEADS.length) * 100,
  ),
};

// ── Pipeline Breakdown ────────────────────────────────────────────────────────

export const PIPELINE_BREAKDOWN = {
  hot:    DUMMY_LEADS.filter((l) => l.classification === 'Hot').length,
  warm:   DUMMY_LEADS.filter((l) => l.classification === 'Warm').length,
  cold:   DUMMY_LEADS.filter((l) => l.classification === 'Cold').length,
  reject: DUMMY_LEADS.filter((l) => l.classification === 'Reject').length,
};

// ── Activity Feed ─────────────────────────────────────────────────────────────

export type ActivityEventType = 'enriched' | 'score' | 'outreach' | 'qualified';

export interface ActivityEvent {
  id: string;
  type: ActivityEventType;
  text: string;
  time: string;
}

export const ACTIVITY_FEED: ActivityEvent[] = [
  {
    id: 'act-1',
    type: 'enriched',
    text: 'Sarah Chen was enriched with 12 new data points',
    time: '2 min ago',
  },
  {
    id: 'act-2',
    type: 'score',
    text: "Marcus Reyes' ICP score updated to 74",
    time: '18 min ago',
  },
  {
    id: 'act-3',
    type: 'outreach',
    text: 'Outreach email sent to David Kim',
    time: '1 hr ago',
  },
  {
    id: 'act-4',
    type: 'qualified',
    text: 'Sarah Chen marked as Qualified',
    time: '2 hr ago',
  },
  {
    id: 'act-5',
    type: 'enriched',
    text: "James O'Brien was enriched with 8 new data points",
    time: '4 hr ago',
  },
];
